# Generated by Django 3.2.12 on 2025-01-05 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('aluguel', 'Aluguel'), ('venda', 'Venda')], max_length=50, verbose_name='Tipo de Contrato')),
                ('valor', models.FloatField(verbose_name='Valor a ser Pago Mensalmente')),
                ('forma_pagamento', models.CharField(choices=[('boleto', 'Boleto'), ('cartao', 'Cartão de Crédito'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária')], max_length=50, verbose_name='Forma de Pagamento')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='ativo', max_length=50, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='imovel.imovel', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
