# Generated by Django 5.1.4 on 2025-01-14 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="O CPF deve estar no formato: '000.000.000-00'.",
                        regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telefone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="O telefone deve estar no formato: '+999999999'. Até 15 dígitos são permitidos.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Telefone",
            ),
        ),
    ]
